-- Migration to standardized sources
-- Run this after creating the standardized_sources table

-- Insert feeling mappings
INSERT INTO feeling_standardized_sources (feeling_slug, source_id, category) VALUES
    ('anxious', 15, 'Support Networks & Connection'),
    ('anxious', 9, 'Support Networks & Connection'),
    ('anxious', 7, 'Support Networks & Connection'),
    ('anxious', 16, 'Support Networks & Connection'),
    ('anxious', 23, 'Support Networks & Connection'),
    ('anxious', 13, 'Boundaries & Guilt Management'),
    ('anxious', 24, 'Boundaries & Guilt Management'),
    ('anxious', 8, 'Boundaries & Guilt Management'),
    ('anxious', 27, 'Therapy, Coaching & Professional Support'),
    ('anxious', 7, 'Therapy, Coaching & Professional Support'),
    ('anxious', 8, 'Therapy, Coaching & Professional Support'),
    ('anxious', 20, 'Rest & Self-Compassion'),
    ('anxious', 27, 'Strategies for Managing Anxiety'),
    ('anxious', 11, 'Strategies for Managing Anxiety'),
    ('anxious', 24, 'Strategies for Managing Anxiety'),
    ('anxious', 36, 'Strategies for Managing Anxiety'),
    ('anxious', 5, 'Rest & Self-Compassion'),
    ('anxious', 28, 'Therapy, Coaching & Professional Support'),
    ('anxious', 9, 'Boundaries & Guilt Management'),
    ('anxious', 9, 'Rest & Self-Compassion'),
    ('anxious', 6, 'Support Networks & Connection'),
    ('anxious', 3, 'Rest & Self-Compassion'),
    ('anxious', 6, 'Therapy, Coaching & Professional Support'),
    ('anxious', 1, 'Rest & Self-Compassion'),
    ('anxious', 2, 'Strategies for Managing Anxiety'),
    ('anxious', 1, 'Strategies for Managing Anxiety'),
    ('anxious', 4, 'Therapy, Coaching & Professional Support'),
    ('anxious', 4, 'Rest & Self-Compassion'),
    ('ashamed', 28, 'Understanding & Confronting Shame'),
    ('ashamed', 8, 'Understanding & Confronting Shame'),
    ('ashamed', 7, 'Understanding & Confronting Shame'),
    ('ashamed', 30, 'Understanding & Confronting Shame'),
    ('ashamed', 24, 'Understanding & Confronting Shame'),
    ('ashamed', 34, 'Understanding & Confronting Shame'),
    ('ashamed', 27, 'Understanding & Confronting Shame'),
    ('ashamed', 9, 'Self-Compassion & Self-Forgiveness'),
    ('ashamed', 10, 'Self-Compassion & Self-Forgiveness'),
    ('ashamed', 20, 'Self-Compassion & Self-Forgiveness'),
    ('ashamed', 11, 'Self-Compassion & Self-Forgiveness'),
    ('ashamed', 36, 'Physical & Emotional Release'),
    ('ashamed', 15, 'Physical & Emotional Release'),
    ('ashamed', 31, 'Addressing the Roots of Shame'),
    ('ashamed', 25, 'Understanding & Confronting Shame'),
    ('ashamed', 6, 'Understanding & Confronting Shame'),
    ('ashamed', 9, 'Physical & Emotional Release'),
    ('anxious', 3, 'Strategies for Managing Anxiety'),
    ('ashamed', 3, 'Understanding & Confronting Shame'),
    ('ashamed', 1, 'Self-Compassion & Self-Forgiveness'),
    ('ashamed', 12, 'Self-Compassion & Self-Forgiveness'),
    ('ashamed', 18, 'Physical & Emotional Release'),
    ('ashamed', 2, 'Physical & Emotional Release'),
    ('ashamed', 5, 'Understanding & Confronting Shame'),
    ('burned_out', 1, 'Understanding Burnout & Energy Depletion'),
    ('ashamed', 4, 'Addressing the Roots of Shame'),
    ('burned_out', 9, 'Understanding Burnout & Energy Depletion'),
    ('burned_out', 16, 'Understanding Burnout & Energy Depletion'),
    ('burned_out', 14, 'Brain Clutter, Systems, & Recovery'),
    ('burned_out', 37, 'Brain Clutter, Systems, & Recovery'),
    ('burned_out', 19, 'Brain Clutter, Systems, & Recovery'),
    ('burned_out', 10, 'Tiny Steps, Self-Compassion, and Reframing'),
    ('burned_out', 11, 'Emotions, Guilt & ADHD Recovery'),
    ('burned_out', 20, 'Emotions, Guilt & ADHD Recovery'),
    ('defeated', 25, 'Shame, Self-Blame & Inner Critics'),
    ('defeated', 28, 'Shame, Self-Blame & Inner Critics'),
    ('defeated', 23, 'Shame, Self-Blame & Inner Critics'),
    ('defeated', 24, 'Limiting Beliefs, Inner Narratives & Identity'),
    ('defeated', 46, 'Limiting Beliefs, Inner Narratives & Identity'),
    ('defeated', 13, 'Limiting Beliefs, Inner Narratives & Identity'),
    ('defeated', 32, 'Limiting Beliefs, Inner Narratives & Identity'),
    ('defeated', 7, 'Emotional Overload, Hopelessness & Burnout'),
    ('defeated', 16, 'Emotional Overload, Hopelessness & Burnout'),
    ('defeated', 30, 'Emotional Overload, Hopelessness & Burnout'),
    ('burned_out', 5, 'Brain Clutter, Systems, & Recovery'),
    ('burned_out', 12, 'Tiny Steps, Self-Compassion, and Reframing'),
    ('burned_out', 2, 'Tiny Steps, Self-Compassion, and Reframing'),
    ('defeated', 3, 'Shame, Self-Blame & Inner Critics'),
    ('defeated', 6, 'Shame, Self-Blame & Inner Critics'),
    ('defeated', 18, 'Limiting Beliefs, Inner Narratives & Identity'),
    ('defeated', 5, 'Emotional Overload, Hopelessness & Burnout'),
    ('defeated', 4, 'Shame, Self-Blame & Inner Critics'),
    ('defeated', 10, 'Reframing, Agency & Tiny Action'),
    ('defeated', 19, 'Reframing, Agency & Tiny Action'),
    ('defeated', 14, 'Reframing, Agency & Tiny Action'),
    ('defeated', 17, 'Validation, Hope & Emotional Processing'),
    ('defeated', 11, 'Validation, Hope & Emotional Processing'),
    ('defeated', 8, 'Validation, Hope & Emotional Processing'),
    ('drained', 10, 'Rebuilding Hope & Addressing Hopelessness'),
    ('drained', 24, 'Rebuilding Hope & Addressing Hopelessness'),
    ('drained', 7, 'Rebuilding Hope & Addressing Hopelessness'),
    ('drained', 32, 'Rebuilding Hope & Addressing Hopelessness'),
    ('drained', 25, 'Rebuilding Hope & Addressing Hopelessness'),
    ('drained', 17, 'Reflection, Writing, & Emotional Processing'),
    ('drained', 9, 'Body Awareness, Interoception & Emotional Reframing'),
    ('drained', 11, 'Body Awareness, Interoception & Emotional Reframing'),
    ('defeated', 15, 'Validation, Hope & Emotional Processing'),
    ('drained', 5, 'Reflection, Writing, & Emotional Processing'),
    ('drained', 15, 'Reflection, Writing, & Emotional Processing'),
    ('drained', 15, 'Body Awareness, Interoception & Emotional Reframing'),
    ('defeated', 12, 'Reframing, Agency & Tiny Action'),
    ('defeated', 2, 'Reframing, Agency & Tiny Action'),
    ('defeated', 1, 'Reframing, Agency & Tiny Action'),
    ('drained', 2, 'Reflection, Writing, & Emotional Processing'),
    ('drained', 2, 'Body Awareness, Interoception & Emotional Reframing'),
    ('drained', 1, 'Clearing Clutter with Brain Dumps'),
    ('drained', 3, 'Clearing Clutter with Brain Dumps'),
    ('drained', 4, 'Rebuilding Hope & Addressing Hopelessness'),
    ('drained', 7, 'Reducing Demands & Taking Baby Steps'),
    ('drained', 19, 'Reducing Demands & Taking Baby Steps'),
    ('forgetful', 9, 'Working Memory, Cognitive Load & ADHD'),
    ('forgetful', 27, 'Working Memory, Cognitive Load & ADHD'),
    ('forgetful', 16, 'Working Memory, Cognitive Load & ADHD'),
    ('forgetful', 14, 'Building Better Systems & External Memory'),
    ('forgetful', 37, 'Building Better Systems & External Memory'),
    ('forgetful', 16, 'Building Better Systems & External Memory'),
    ('forgetful', 19, 'Building Better Systems & External Memory'),
    ('forgetful', 7, 'Writing Things Down & Reminder Strategies'),
    ('forgetful', 7, 'Baby Steps & Protecting Energy'),
    ('forgetful', 28, 'Energy-Conserving Systems & Real-Time Healing'),
    ('drained', 5, 'Reducing Demands & Taking Baby Steps'),
    ('forgetful', 25, 'Baby Steps & Protecting Energy'),
    ('drained', 3, 'Reducing Demands & Taking Baby Steps'),
    ('drained', 12, 'Reducing Demands & Taking Baby Steps'),
    ('forgetful', 3, 'Working Memory, Cognitive Load & ADHD'),
    ('forgetful', 6, 'Writing Things Down & Reminder Strategies'),
    ('drained', 25, 'Reducing Demands & Taking Baby Steps'),
    ('forgetful', 3, 'Building Better Systems & External Memory'),
    ('forgetful', 12, 'Baby Steps & Protecting Energy'),
    ('forgetful', 1, 'Energy-Conserving Systems & Real-Time Healing'),
    ('forgetful', 5, 'Building Better Systems & External Memory'),
    ('forgetful', 4, 'Energy-Conserving Systems & Real-Time Healing'),
    ('frustrated', 10, 'Emotions as Signals, Not Enemies'),
    ('frustrated', 9, 'Emotions as Signals, Not Enemies'),
    ('frustrated', 11, 'Emotions as Signals, Not Enemies'),
    ('frustrated', 23, 'Boundaries, Overload & Powerlessness'),
    ('frustrated', 24, 'Boundaries, Overload & Powerlessness'),
    ('frustrated', 13, 'Boundaries, Overload & Powerlessness'),
    ('frustrated', 8, 'Boundaries, Overload & Powerlessness'),
    ('frustrated', 14, 'Externalizing Emotions & Reducing Self-Blame'),
    ('frustrated', 37, 'Externalizing Emotions & Reducing Self-Blame'),
    ('frustrated', 7, 'Externalizing Emotions & Reducing Self-Blame'),
    ('frustrated', 27, 'Externalizing Emotions & Reducing Self-Blame'),
    ('frustrated', 36, 'Externalizing Emotions & Reducing Self-Blame'),
    ('frustrated', 17, 'Externalizing Emotions & Reducing Self-Blame'),
    ('frustrated', 16, 'Externalizing Emotions & Reducing Self-Blame'),
    ('frustrated', 19, 'Externalizing Emotions & Reducing Self-Blame'),
    ('forgetful', 3, 'Energy-Conserving Systems & Real-Time Healing'),
    ('frustrated', 28, 'Boundaries, Overload & Powerlessness'),
    ('frustrated', 2, 'Emotions as Signals, Not Enemies'),
    ('frustrated', 25, 'Externalizing Emotions & Reducing Self-Blame'),
    ('frustrated', 1, 'Boundaries, Overload & Powerlessness'),
    ('frustrated', 1, 'Externalizing Emotions & Reducing Self-Blame'),
    ('frustrated', 3, 'Externalizing Emotions & Reducing Self-Blame'),
    ('frustrated', 6, 'Externalizing Emotions & Reducing Self-Blame'),
    ('frustrated', 5, 'Externalizing Emotions & Reducing Self-Blame'),
    ('guilty', 32, 'Understanding Guilt as a Signal (Not a Verdict)'),
    ('guilty', 9, 'Understanding Guilt as a Signal (Not a Verdict)'),
    ('guilty', 11, 'Understanding Guilt as a Signal (Not a Verdict)'),
    ('guilty', 10, 'Understanding Guilt as a Signal (Not a Verdict)'),
    ('guilty', 27, 'Self-Compassion & Reframing Shame'),
    ('guilty', 7, 'Self-Compassion & Reframing Shame'),
    ('guilty', 8, 'Self-Compassion & Reframing Shame'),
    ('guilty', 46, 'Self-Compassion & Reframing Shame'),
    ('guilty', 37, 'Gentle Action & Systems for Support'),
    ('guilty', 14, 'Gentle Action & Systems for Support'),
    ('guilty', 16, 'Gentle Action & Systems for Support'),
    ('guilty', 17, 'Gentle Action & Systems for Support'),
    ('guilty', 13, 'Gentle Action & Systems for Support'),
    ('guilty', 19, 'Gentle Action & Systems for Support'),
    ('guilty', 4, 'Boundaries, Capacity & Saying No'),
    ('guilty', 3, 'Gentle Action & Systems for Support'),
    ('guilty', 28, 'Self-Compassion & Reframing Shame'),
    ('guilty', 18, 'Understanding Guilt as a Signal (Not a Verdict)'),
    ('guilty', 25, 'Self-Compassion & Reframing Shame'),
    ('guilty', 1, 'Self-Compassion & Reframing Shame'),
    ('guilty', 6, 'Self-Compassion & Reframing Shame'),
    ('guilty', 12, 'Gentle Action & Systems for Support'),
    ('guilty', 1, 'Boundaries, Capacity & Saying No'),
    ('guilty', 4, 'Understanding Guilt as a Signal (Not a Verdict)'),
    ('guilty', 8, 'Boundaries, Capacity & Saying No'),
    ('guilty', 13, 'Boundaries, Capacity & Saying No'),
    ('guilty', 36, 'Emotional Context & Community Understanding'),
    ('guilty', 20, 'Emotional Context & Community Understanding'),
    ('guilty', 48, 'Emotional Context & Community Understanding'),
    ('hopeless', 10, 'Recognizing Hopelessness as a Signal'),
    ('hopeless', 9, 'Recognizing Hopelessness as a Signal'),
    ('hopeless', 17, 'Recognizing Hopelessness as a Signal'),
    ('hopeless', 46, 'How ADHD Fuels Hopelessness'),
    ('hopeless', 8, 'How ADHD Fuels Hopelessness'),
    ('hopeless', 23, 'How ADHD Fuels Hopelessness'),
    ('hopeless', 24, 'Reframing, Micro-Steps & Meaning-Making'),
    ('hopeless', 32, 'Reframing, Micro-Steps & Meaning-Making'),
    ('hopeless', 15, 'Recognizing Hopelessness as a Signal'),
    ('hopeless', 28, 'How ADHD Fuels Hopelessness'),
    ('hopeless', 1, 'How ADHD Fuels Hopelessness'),
    ('hopeless', 9, 'How ADHD Fuels Hopelessness'),
    ('hopeless', 3, 'How ADHD Fuels Hopelessness'),
    ('hopeless', 12, 'Reframing, Micro-Steps & Meaning-Making'),
    ('guilty', 5, 'Emotional Context & Community Understanding'),
    ('hopeless', 5, 'Reframing, Micro-Steps & Meaning-Making'),
    ('hopeless', 17, 'You Don’t Have to Face This Alone'),
    ('hopeless', 8, 'You Don’t Have to Face This Alone'),
    ('hopeless', 46, 'You Don’t Have to Face This Alone'),
    ('lonely', 46, 'Why ADHD Makes Loneliness Worse'),
    ('lonely', 7, 'Why ADHD Makes Loneliness Worse'),
    ('lonely', 8, 'Emotional Dysregulation, Shame & Self-Protection'),
    ('lonely', 24, 'Emotional Dysregulation, Shame & Self-Protection'),
    ('lonely', 10, 'Tools for Self-Compassion, Naming & Externalizing'),
    ('lonely', 13, 'Tools for Self-Compassion, Naming & Externalizing'),
    ('lonely', 17, 'Tools for Self-Compassion, Naming & Externalizing'),
    ('hopeless', 1, 'You Don’t Have to Face This Alone'),
    ('hopeless', 5, 'You Don’t Have to Face This Alone'),
    ('lonely', 15, 'Emotional Dysregulation, Shame & Self-Protection'),
    ('hopeless', 3, 'You Don’t Have to Face This Alone'),
    ('lonely', 33, 'Why ADHD Makes Loneliness Worse'),
    ('lonely', 9, 'Why ADHD Makes Loneliness Worse'),
    ('hopeless', 6, 'You Don’t Have to Face This Alone'),
    ('hopeless', 25, 'You Don’t Have to Face This Alone'),
    ('lonely', 1, 'Why ADHD Makes Loneliness Worse'),
    ('lonely', 2, 'Emotional Dysregulation, Shame & Self-Protection'),
    ('lonely', 6, 'Tools for Self-Compassion, Naming & Externalizing'),
    ('lonely', 5, 'Why ADHD Makes Loneliness Worse'),
    ('lonely', 4, 'Emotional Dysregulation, Shame & Self-Protection'),
    ('hopeless', 4, 'You Don’t Have to Face This Alone'),
    ('lonely', 11, 'Tools for Self-Compassion, Naming & Externalizing'),
    ('lonely', 32, 'Tools for Self-Compassion, Naming & Externalizing'),
    ('lonely', 30, 'Making Connection Possible Again'),
    ('lonely', 46, 'Making Connection Possible Again'),
    ('mental_fog', 16, 'Executive Function, Attention, and Working Memory'),
    ('mental_fog', 27, 'Executive Function, Attention, and Working Memory'),
    ('mental_fog', 19, 'Executive Function, Attention, and Working Memory'),
    ('mental_fog', 22, 'Executive Function, Attention, and Working Memory'),
    ('mental_fog', 46, 'Emotional Overwhelm, Shame, and Dysregulation'),
    ('mental_fog', 30, 'Emotional Overwhelm, Shame, and Dysregulation'),
    ('mental_fog', 36, 'Nutrition, Movement, and Lifestyle'),
    ('mental_fog', 20, 'Nutrition, Movement, and Lifestyle'),
    ('mental_fog', 15, 'Nutrition, Movement, and Lifestyle'),
    ('mental_fog', 14, 'Mindfulness, Systems, and Mental Load'),
    ('mental_fog', 34, 'Identity, Hormones, and Development'),
    ('mental_fog', 28, 'Emotional Overwhelm, Shame, and Dysregulation'),
    ('mental_fog', 31, 'Mindfulness, Systems, and Mental Load'),
    ('lonely', 2, 'Making Connection Possible Again'),
    ('scattered', 3, 'Tiny Steps When You’re All Over the Place'),
    ('mental_fog', 6, 'Emotional Overwhelm, Shame, and Dysregulation'),
    ('mental_fog', 3, 'Emotional Overwhelm, Shame, and Dysregulation'),
    ('mental_fog', 5, 'Mindfulness, Systems, and Mental Load'),
    ('mental_fog', 1, 'Mindfulness, Systems, and Mental Load'),
    ('mental_fog', 23, 'Identity, Hormones, and Development'),
    ('mental_fog', 48, 'Identity, Hormones, and Development'),
    ('mental_fog', 8, 'Identity, Hormones, and Development'),
    ('mental_fog', 7, 'Identity, Hormones, and Development'),
    ('misunderstood', 30, 'Why ADHD Makes You Feel Misunderstood'),
    ('misunderstood', 7, 'Rejection, Shame, and Shutdown'),
    ('misunderstood', 32, 'Rejection, Shame, and Shutdown'),
    ('misunderstood', 10, 'Reframing, Self-Compassion, and Communication'),
    ('misunderstood', 24, 'Reframing, Self-Compassion, and Communication'),
    ('misunderstood', 17, 'Reframing, Self-Compassion, and Communication'),
    ('misunderstood', 13, 'Reframing, Self-Compassion, and Communication'),
    ('misunderstood', 8, 'Identity, Visibility & the Pain of Not Being Seen'),
    ('misunderstood', 5, 'Healing Through Externalization & Support'),
    ('mental_fog', 25, 'Identity, Hormones, and Development'),
    ('mental_fog', 18, 'Identity, Hormones, and Development'),
    ('misunderstood', 9, 'Why ADHD Makes You Feel Misunderstood'),
    ('misunderstood', 3, 'Why ADHD Makes You Feel Misunderstood'),
    ('misunderstood', 1, 'Reframing, Self-Compassion, and Communication'),
    ('misunderstood', 2, 'Identity, Visibility & the Pain of Not Being Seen'),
    ('misunderstood', 6, 'Healing Through Externalization & Support'),
    ('misunderstood', 4, 'Rejection, Shame, and Shutdown'),
    ('numb', 15, 'Why ADHD Can Lead to Numbness'),
    ('numb', 11, 'Why ADHD Can Lead to Numbness'),
    ('numb', 28, 'Burnout, Shame & Emotional Shutdown'),
    ('numb', 8, 'Burnout, Shame & Emotional Shutdown'),
    ('numb', 15, 'Tools to Reconnect Gently'),
    ('overstimulated', 15, 'Why ADHD Gets Overstimulated So Easily'),
    ('overstimulated', 11, 'Why ADHD Gets Overstimulated So Easily'),
    ('overstimulated', 34, 'Why ADHD Gets Overstimulated So Easily'),
    ('overstimulated', 20, 'Dopamine-Seeking, Adrenaline & Sensory Spiral'),
    ('misunderstood', 18, 'Healing Through Externalization & Support'),
    ('numb', 25, 'Tools to Reconnect Gently'),
    ('overstimulated', 25, 'Why ADHD Gets Overstimulated So Easily'),
    ('numb', 3, 'Tools to Reconnect Gently'),
    ('misunderstood', 27, 'Healing Through Externalization & Support'),
    ('overstimulated', 33, 'Dopamine-Seeking, Adrenaline & Sensory Spiral'),
    ('numb', 9, 'Tools to Reconnect Gently'),
    ('overstimulated', 9, 'Why ADHD Gets Overstimulated So Easily'),
    ('numb', 2, 'Why ADHD Can Lead to Numbness'),
    ('misunderstood', 25, 'Healing Through Externalization & Support'),
    ('overstimulated', 3, 'Why ADHD Gets Overstimulated So Easily'),
    ('numb', 12, 'Tools to Reconnect Gently'),
    ('overstimulated', 18, 'Why ADHD Gets Overstimulated So Easily'),
    ('overstimulated', 36, 'Dopamine-Seeking, Adrenaline & Sensory Spiral'),
    ('overwhelmed', 20, 'Understanding ADHD Overwhelm'),
    ('overwhelmed', 16, 'Understanding ADHD Overwhelm'),
    ('overwhelmed', 8, 'Understanding ADHD Overwhelm'),
    ('overwhelmed', 15, 'Understanding ADHD Overwhelm'),
    ('overstimulated', 13, 'Recognizing Triggers & Early Warnings'),
    ('overwhelmed', 12, 'Baby Steps & Reducing Demands'),
    ('overstimulated', 2, 'Recognizing Triggers & Early Warnings'),
    ('overstimulated', 9, 'Sensory Tools & Nervous System Soothing'),
    ('overwhelmed', 3, 'Externalize, Organize, Simplify'),
    ('overstimulated', 31, 'Reducing Demands, Externalizing, & Getting Support'),
    ('overwhelmed', 5, 'Externalize, Organize, Simplify'),
    ('overstimulated', 8, 'Reducing Demands, Externalizing, & Getting Support'),
    ('overstimulated', 6, 'Reducing Demands, Externalizing, & Getting Support'),
    ('overwhelmed', 14, 'Externalize, Organize, Simplify'),
    ('overwhelmed', 37, 'Externalize, Organize, Simplify'),
    ('overwhelmed', 19, 'Externalize, Organize, Simplify'),
    ('overstimulated', 15, 'Sensory Tools & Nervous System Soothing'),
    ('overstimulated', 48, 'Sensory Tools & Nervous System Soothing'),
    ('overwhelmed', 18, 'Understanding ADHD Overwhelm'),
    ('overwhelmed', 6, 'Externalize, Organize, Simplify'),
    ('rejected', 34, 'Understanding Rejection Sensitivity & Emotional Pain'),
    ('rejected', 7, 'Understanding Rejection Sensitivity & Emotional Pain'),
    ('rejected', 20, 'Self-Compassion, Shame, and Inner Critic Work'),
    ('rejected', 24, 'Emotional Resilience, Identity & Boundaries'),
    ('rejected', 30, 'Emotional Resilience, Identity & Boundaries'),
    ('rejected', 17, 'Emotional Resilience, Identity & Boundaries'),
    ('scattered', 27, 'Tiny Steps When You’re All Over the Place'),
    ('rejected', 6, 'Understanding Rejection Sensitivity & Emotional Pain'),
    ('rejected', 25, 'Self-Compassion, Shame, and Inner Critic Work'),
    ('overwhelmed', 1, 'Baby Steps & Reducing Demands'),
    ('overwhelmed', 10, 'Baby Steps & Reducing Demands'),
    ('rejected', 5, 'Emotional Resilience, Identity & Boundaries'),
    ('rejected', 18, 'Understanding Rejection Sensitivity & Emotional Pain'),
    ('overwhelmed', 17, 'Emotional Regulation & Support'),
    ('rejected', 9, 'Understanding Rejection Sensitivity & Emotional Pain'),
    ('overwhelmed', 9, 'Emotional Regulation & Support'),
    ('rejected', 3, 'Understanding Rejection Sensitivity & Emotional Pain'),
    ('rejected', 1, 'Self-Compassion, Shame, and Inner Critic Work'),
    ('rejected', 2, 'Self-Compassion, Shame, and Inner Critic Work'),
    ('overwhelmed', 2, 'Baby Steps & Reducing Demands'),
    ('rejected', 31, 'Self-Compassion, Shame, and Inner Critic Work'),
    ('rejected', 13, 'Emotional Resilience, Identity & Boundaries'),
    ('rejected', 10, 'Integration & Healing'),
    ('restless', 7, 'Emotional Turbulence, Hopelessness & Disconnection'),
    ('restless', 11, 'Emotional Turbulence, Hopelessness & Disconnection'),
    ('restless', 23, 'Emotional Turbulence, Hopelessness & Disconnection'),
    ('restless', 11, 'Externalization: Free-Writing, Body Mapping & Naming Emotions'),
    ('restless', 14, 'Brain Dumping & External Processing'),
    ('restless', 10, 'Reclaiming Control: Doing Less, Resting More'),
    ('restless', 19, 'Micro-Steps, Baby Steps & Self-Pacing'),
    ('rejected', 15, 'Integration & Healing'),
    ('restless', 15, 'Emotional Turbulence, Hopelessness & Disconnection'),
    ('restless', 15, 'Externalization: Free-Writing, Body Mapping & Naming Emotions'),
    ('rejected', 2, 'Integration & Healing'),
    ('restless', 9, 'Externalization: Free-Writing, Body Mapping & Naming Emotions'),
    ('restless', 1, 'Emotional Turbulence, Hopelessness & Disconnection'),
    ('restless', 25, 'Micro-Steps, Baby Steps & Self-Pacing'),
    ('restless', 3, 'Emotional Turbulence, Hopelessness & Disconnection'),
    ('restless', 6, 'Emotional Turbulence, Hopelessness & Disconnection'),
    ('restless', 1, 'Externalization: Free-Writing, Body Mapping & Naming Emotions'),
    ('restless', 2, 'Externalization: Free-Writing, Body Mapping & Naming Emotions'),
    ('restless', 5, 'Brain Dumping & External Processing'),
    ('restless', 12, 'Micro-Steps, Baby Steps & Self-Pacing'),
    ('restless', 31, 'Reclaiming Control: Doing Less, Resting More'),
    ('scattered', 19, 'Executive Dysfunction, Attention, and the Scattered Mind'),
    ('scattered', 34, 'Executive Dysfunction, Attention, and the Scattered Mind'),
    ('scattered', 16, 'Executive Dysfunction, Attention, and the Scattered Mind'),
    ('scattered', 27, 'Executive Dysfunction, Attention, and the Scattered Mind'),
    ('scattered', 8, 'Executive Dysfunction, Attention, and the Scattered Mind'),
    ('scattered', 7, 'Executive Dysfunction, Attention, and the Scattered Mind'),
    ('scattered', 14, 'Brain Dumps & Externalizing Chaos'),
    ('scattered', 11, 'Reconnecting with the Body & Reframing Emotion'),
    ('scattered', 10, 'Scaling Back & Finding Calm'),
    ('scattered', 31, 'Scaling Back & Finding Calm'),
    ('scattered', 18, 'Executive Dysfunction, Attention, and the Scattered Mind'),
    ('scattered', 6, 'Executive Dysfunction, Attention, and the Scattered Mind'),
    ('scattered', 9, 'Reconnecting with the Body & Reframing Emotion'),
    ('scattered', 25, 'Tiny Steps When You’re All Over the Place'),
    ('scattered', 28, 'Executive Dysfunction, Attention, and the Scattered Mind'),
    ('scattered', 3, 'Executive Dysfunction, Attention, and the Scattered Mind'),
    ('scattered', 2, 'Executive Dysfunction, Attention, and the Scattered Mind'),
    ('scattered', 1, 'Brain Dumps & Externalizing Chaos'),
    ('scattered', 2, 'Reconnecting with the Body & Reframing Emotion'),
    ('scattered', 6, 'Reconnecting with the Body & Reframing Emotion'),
    ('scattered', 1, 'Reconnecting with the Body & Reframing Emotion'),
    ('scattered', 5, 'Executive Dysfunction, Attention, and the Scattered Mind'),
    ('scattered', 12, 'Tiny Steps When You’re All Over the Place'),
    ('scattered', 5, 'Brain Dumps & Externalizing Chaos'),
    ('scattered', 4, 'Scaling Back & Finding Calm'),
    ('scattered', 19, 'Tiny Steps When You’re All Over the Place'),
    ('stressed', 15, 'Acknowledge & Validate Your Emotions'),
    ('stressed', 16, 'Acknowledge & Validate Your Emotions'),
    ('stressed', 11, 'Acknowledge & Validate Your Emotions'),
    ('stressed', 15, 'Move & Ground Your Body'),
    ('stressed', 20, 'Move & Ground Your Body'),
    ('stressed', 11, 'Move & Ground Your Body'),
    ('stressed', 16, 'Rethink & Reframe Tasks'),
    ('stressed', 24, 'Reduce Demands & Reclaim a Tiny Sense of Control'),
    ('stressed', 13, 'Set Boundaries, Reach Out, and Let Go'),
    ('stressed', 7, 'Set Boundaries, Reach Out, and Let Go'),
    ('stressed', 8, 'Set Boundaries, Reach Out, and Let Go'),
    ('stressed', 16, 'Set Boundaries, Reach Out, and Let Go'),
    ('stuck', 10, 'Acknowledge & Process Emotions'),
    ('stressed', 5, 'Set Boundaries, Reach Out, and Let Go'),
    ('stressed', 9, 'Acknowledge & Validate Your Emotions'),
    ('stressed', 25, 'Acknowledge & Validate Your Emotions'),
    ('stressed', 9, 'Move & Ground Your Body'),
    ('stressed', 2, 'Acknowledge & Validate Your Emotions'),
    ('stressed', 12, 'Rethink & Reframe Tasks'),
    ('stressed', 9, 'Set Boundaries, Reach Out, and Let Go'),
    ('stuck', 9, 'Acknowledge & Process Emotions'),
    ('stressed', 3, 'Rethink & Reframe Tasks'),
    ('stressed', 2, 'Rethink & Reframe Tasks'),
    ('stressed', 1, 'Reduce Demands & Reclaim a Tiny Sense of Control'),
    ('stressed', 2, 'Reduce Demands & Reclaim a Tiny Sense of Control'),
    ('stressed', 6, 'Set Boundaries, Reach Out, and Let Go'),
    ('stuck', 1, 'Acknowledge & Process Emotions'),
    ('stuck', 2, 'Acknowledge & Process Emotions'),
    ('stressed', 4, 'Set Boundaries, Reach Out, and Let Go'),
    ('stuck', 11, 'Acknowledge & Process Emotions'),
    ('stuck', 16, 'Acknowledge & Process Emotions'),
    ('stuck', 15, 'Acknowledge & Process Emotions'),
    ('stuck', 32, 'Acknowledge & Process Emotions'),
    ('stuck', 23, 'Reduce Demands & Reclaim Control'),
    ('stuck', 13, 'Reduce Demands & Reclaim Control'),
    ('stuck', 14, 'Reduce Demands & Reclaim Control'),
    ('stuck', 7, 'Reduce Demands & Reclaim Control'),
    ('stuck', 27, 'Reduce Demands & Reclaim Control'),
    ('stuck', 16, 'Reduce Demands & Reclaim Control'),
    ('stuck', 19, 'Reduce Demands & Reclaim Control'),
    ('stuck', 17, 'Embrace Curiosity & Trust the Process'),
    ('stuck', 8, 'Embrace Curiosity & Trust the Process'),
    ('stuck', 25, 'Reduce Demands & Reclaim Control'),
    ('stuck', 4, 'Reduce Demands & Reclaim Control'),
    ('stuck', 3, 'Reduce Demands & Reclaim Control'),
    ('stuck', 18, 'Acknowledge & Process Emotions'),
    ('stuck', 1, 'Reduce Demands & Reclaim Control'),
    ('stuck', 12, 'Reduce Demands & Reclaim Control'),
    ('stuck', 2, 'Reduce Demands & Reclaim Control'),
    ('stuck', 6, 'Reduce Demands & Reclaim Control'),
    ('stuck', 2, 'Embrace Curiosity & Trust the Process'),
    ('anxious', 4, 'Support Networks & Connection'),
    ('guilty', 33, 'Emotional Context & Community Understanding'),
    ('defeated', 33, 'Emotional Overload, Hopelessness & Burnout'),
    ('frustrated', 15, 'Externalizing Emotions & Reducing Self-Blame'),
    ('misunderstood', 33, 'Rejection, Shame, and Shutdown'),
    ('scattered', 33, 'Executive Dysfunction, Attention, and the Scattered Mind'),
    ('lonely', 4, 'Making Connection Possible Again'),
    ('numb', 4, 'Burnout, Shame & Emotional Shutdown'),
    ('rejected', 4, 'Self-Compassion, Shame, and Inner Critic Work'),
    ('overstimulated', 4, 'Recognizing Triggers & Early Warnings'),
    ('scattered', 15, 'Reconnecting with the Body & Reframing Emotion'),
    ('anxious', 2, 'Support Networks & Connection'),
    ('forgetful', 25, 'Working Memory, Cognitive Load & ADHD'),
    ('burned_out', 3, 'Understanding Burnout & Energy Depletion'),
    ('overstimulated', 19, 'Reducing Demands, Externalizing, & Getting Support'),
    ('overstimulated', 7, 'Sensory Tools & Nervous System Soothing'),
    ('overstimulated', 34, 'Sensory Tools & Nervous System Soothing'),
    ('overwhelmed', 7, 'Emotional Regulation & Support'),
    ('overwhelmed', 13, 'Emotional Regulation & Support'),
    ('overwhelmed', 30, 'Emotional Regulation & Support'),
    ('rejected', 4, 'Integration & Healing'),
    ('lonely', 25, 'Emotional Dysregulation, Shame & Self-Protection'),
    ('numb', 9, 'Why ADHD Can Lead to Numbness'),
    ('stressed', 25, 'Rethink & Reframe Tasks'),
    ('overwhelmed', 25, 'Understanding ADHD Overwhelm'),
    ('forgetful', 3, 'Writing Things Down & Reminder Strategies'),
    ('restless', 3, 'Brain Dumping & External Processing'),
    ('scattered', 3, 'Brain Dumps & Externalizing Chaos'),
    ('stressed', 3, 'Reduce Demands & Reclaim a Tiny Sense of Control'),
    ('mental_fog', 33, 'Executive Function, Attention, and Working Memory'),
    ('guilty', 2, 'Understanding Guilt as a Signal (Not a Verdict)'),
    ('hopeless', 2, 'Recognizing Hopelessness as a Signal'),
    ('overstimulated', 1, 'Recognizing Triggers & Early Warnings'),
    ('hopeless', 4, 'Reframing, Micro-Steps & Meaning-Making'),
    ('anxious', 4, 'Boundaries & Guilt Management'),
    ('ashamed', 4, 'Self-Compassion & Self-Forgiveness'),
    ('burned_out', 4, 'Understanding Burnout & Energy Depletion'),
    ('frustrated', 4, 'Boundaries, Overload & Powerlessness'),
    ('restless', 4, 'Emotional Turbulence, Hopelessness & Disconnection'),
    ('stressed', 4, 'Acknowledge & Validate Your Emotions'),
    ('overwhelmed', 4, 'Emotional Regulation & Support');

-- Insert barrier mappings
INSERT INTO barrier_standardized_sources (barrier_slug, source_id, category) VALUES
    ('i_dont_know_where_to_start', 4, 'Strategy Systems & Clarity Tools'),
    ('i_dont_know_where_to_start', 5, 'Reframing Inertia & Shrinking Shame'),
    ('i_dont_know_where_to_start', 1, 'Reframing Inertia & Shrinking Shame'),
    ('i_dont_know_where_to_start', 6, 'Understanding ADHD & Task Initiation Challenges'),
    ('i_dont_know_where_to_start', 33, 'Understanding ADHD & Task Initiation Challenges'),
    ('i_feel_frozen', 19, 'Why Freezing Happens'),
    ('i_feel_frozen', 16, 'Why Freezing Happens'),
    ('i_feel_frozen', 15, 'Emotional Root Causes'),
    ('i_feel_frozen', 12, 'Strategies That Help'),
    ('i_feel_frozen', 3, 'Why Freezing Happens'),
    ('i_feel_frozen', 24, 'Emotional Root Causes'),
    ('i_feel_frozen', 2, 'Strategies That Help'),
    ('i_feel_frozen', 28, 'Why Freezing Happens'),
    ('i_feel_frozen', 6, 'Why Freezing Happens'),
    ('i_feel_frozen', 1, 'Strategies That Help'),
    ('i_feel_frozen', 32, 'Emotional Root Causes'),
    ('i_feel_frozen', 5, 'Strategies That Help'),
    ('i_feel_frozen', 4, 'Emotional Root Causes'),
    ('i_dont_have_energy', 28, 'Burnout, Rest & Recovery'),
    ('i_dont_have_energy', 10, 'Motivation, Micro-Steps & Momentum'),
    ('i_run_out_of_steam', 43, 'Understanding ADHD Fatigue & Burnout'),
    ('i_dont_have_energy', 27, 'Understanding ADHD & Energy Drain'),
    ('i_dont_have_energy', 6, 'Nutrition, Movement & Sleep'),
    ('i_dont_have_energy', 10, 'Burnout, Rest & Recovery'),
    ('i_dont_have_energy', 20, 'Understanding ADHD & Energy Drain'),
    ('i_already_failed', 8, 'Why Failure Feels So Final with ADHD'),
    ('i_dont_have_energy', 3, 'Understanding ADHD & Energy Drain'),
    ('i_dont_have_energy', 28, 'Understanding ADHD & Energy Drain'),
    ('i_dont_have_energy', 3, 'Motivation, Micro-Steps & Momentum'),
    ('i_dont_have_energy', 33, 'Nutrition, Movement & Sleep'),
    ('i_dont_have_energy', 7, 'Support, Coaching & Asking for Help'),
    ('i_run_out_of_steam', 1, 'Energy Management & Gentle Productivity'),
    ('i_dont_have_energy', 6, 'Support, Coaching & Asking for Help'),
    ('i_dont_have_energy', 3, 'Support, Coaching & Asking for Help'),
    ('i_dont_know_how', 33, 'Understanding Executive Function and ADHD'),
    ('its_not_urgent', 3, 'Why Urgency Helps ADHD Brains Activate'),
    ('i_forgot', 3, 'ADHD Strategy & System Design'),
    ('i_forgot', 14, 'ADHD Strategy & System Design'),
    ('its_not_urgent', 5, 'Planning Systems, Prompts & Activation Tools'),
    ('i_forgot', 28, 'Emotional Impact of Forgetfulness'),
    ('its_not_urgent', 10, 'Deadlines, Time Blindness & Follow-Through'),
    ('its_not_urgent', 17, 'Deadlines, Time Blindness & Follow-Through'),
    ('i_already_failed', 1, 'Why Failure Feels So Final with ADHD'),
    ('its_not_urgent', 16, 'Why Urgency Helps ADHD Brains Activate'),
    ('its_not_urgent', 12, 'Planning Systems, Prompts & Activation Tools'),
    ('its_not_urgent', 14, 'Planning Systems, Prompts & Activation Tools'),
    ('i_forgot', 6, 'Practical Tools for Remembering'),
    ('its_not_urgent', 6, 'Why Urgency Helps ADHD Brains Activate'),
    ('i_cant_stay_focused', 6, 'Movement, Sensory Support, & Focus Regulation'),
    ('i_cant_stay_focused', 28, 'Mindset, Self-Compassion & Focus Reframing'),
    ('i_dont_have_time', 3, 'Understanding ADHD & Time Blindness'),
    ('i_already_failed', 27, 'Why Failure Feels So Final with ADHD'),
    ('i_already_failed', 9, 'Why Failure Feels So Final with ADHD'),
    ('i_already_failed', 46, 'Why Failure Feels So Final with ADHD'),
    ('i_already_failed', 3, 'Why Failure Feels So Final with ADHD'),
    ('i_already_failed', 6, 'Why Failure Feels So Final with ADHD'),
    ('i_dont_have_time', 3, 'Making Time Visible & Managing Tasks'),
    ('i_already_failed', 5, 'Why Failure Feels So Final with ADHD'),
    ('i_already_failed', 16, 'Turning Failure Into Data'),
    ('i_already_failed', 28, 'Why Failure Feels So Final with ADHD'),
    ('i_already_failed', 4, 'Why Failure Feels So Final with ADHD'),
    ('i_cant_stay_focused', 43, 'Managing Time, Hyperfocus & Mental Energy'),
    ('i_cant_start', 12, 'Break It Down & Externalize the Start'),
    ('i_already_failed', 24, 'Why Failure Feels So Final with ADHD'),
    ('i_already_failed', 7, 'Turning Failure Into Data'),
    ('i_already_failed', 7, 'Support Systems That Help You Reset'),
    ('i_already_failed', 11, 'Turning Failure Into Data'),
    ('i_cant_start', 16, 'Why It’s Hard to Start'),
    ('i_already_failed', 31, 'Turning Failure Into Data'),
    ('i_already_failed', 13, 'Support Systems That Help You Reset'),
    ('i_already_failed', 2, 'Why Failure Feels So Final with ADHD'),
    ('i_cant_start', 1, 'Why It’s Hard to Start'),
    ('i_already_failed', 25, 'Support Systems That Help You Reset'),
    ('i_cant_stay_focused', 27, 'Managing Time, Hyperfocus & Mental Energy'),
    ('i_already_failed', 16, 'Support Systems That Help You Reset'),
    ('i_cant_start', 9, 'Why It’s Hard to Start'),
    ('i_already_failed', 10, 'Turning Failure Into Data'),
    ('i_cant_stay_focused', 6, 'Managing Time, Hyperfocus & Mental Energy'),
    ('i_cant_stay_focused', 33, 'Movement, Sensory Support, & Focus Regulation'),
    ('i_cant_start', 14, 'Break It Down & Externalize the Start'),
    ('i_cant_start', 6, 'Why It’s Hard to Start'),
    ('i_cant_start', 19, 'Break It Down & Externalize the Start'),
    ('i_cant_stay_focused', 7, 'Managing Time, Hyperfocus & Mental Energy'),
    ('i_already_failed', 4, 'Support Systems That Help You Reset'),
    ('i_cant_start', 3, 'Why It’s Hard to Start'),
    ('i_cant_stay_focused', 20, 'Movement, Sensory Support, & Focus Regulation'),
    ('i_already_failed', 2, 'Turning Failure Into Data'),
    ('i_cant_start', 28, 'Why It’s Hard to Start'),
    ('i_cant_stay_focused', 9, 'Understanding ADHD & Attention'),
    ('i_cant_stay_focused', 3, 'Understanding ADHD & Attention'),
    ('i_cant_stay_focused', 3, 'Mindset, Self-Compassion & Focus Reframing'),
    ('i_cant_start', 31, 'Time Tools & Dopamine Tricks'),
    ('i_cant_start', 20, 'Movement, Music, & Novelty'),
    ('i_already_failed', 28, 'Support Systems That Help You Reset'),
    ('i_already_failed', 9, 'Support Systems That Help You Reset'),
    ('i_cant_stay_focused', 6, 'Tools for Managing Distraction & Filtering Noise'),
    ('i_cant_start', 13, 'Get Support: Coaches, Coworkers, & Gentle Voices'),
    ('i_cant_stay_focused', 16, 'Tools for Managing Distraction & Filtering Noise'),
    ('i_already_failed', 6, 'Support Systems That Help You Reset'),
    ('i_cant_start', 33, 'Movement, Music, & Novelty'),
    ('i_cant_stay_focused', 25, 'Understanding ADHD & Attention'),
    ('i_cant_stay_focused', 1, 'Tools for Managing Distraction & Filtering Noise'),
    ('i_cant_stay_focused', 5, 'Mindset, Self-Compassion & Focus Reframing'),
    ('i_cant_stay_focused', 1, 'Mindset, Self-Compassion & Focus Reframing'),
    ('i_cant_start', 32, 'Time Tools & Dopamine Tricks'),
    ('i_cant_start', 2, 'Time Tools & Dopamine Tricks'),
    ('i_cant_start', 25, 'Get Support: Coaches, Coworkers, & Gentle Voices'),
    ('i_cant_stay_focused', 14, 'Tools for Managing Distraction & Filtering Noise'),
    ('i_cant_start', 46, 'Get Support: Coaches, Coworkers, & Gentle Voices'),
    ('i_cant_start', 1, 'Movement, Music, & Novelty'),
    ('i_cant_stay_focused', 5, 'Tools for Managing Distraction & Filtering Noise'),
    ('i_already_failed', 33, 'Support Systems That Help You Reset'),
    ('i_dont_have_time', 10, 'Making Time Visible & Managing Tasks'),
    ('i_dont_have_time', 14, 'Making Time Visible & Managing Tasks'),
    ('i_dont_have_time', 2, 'Making Time Visible & Managing Tasks'),
    ('i_dont_have_time', 12, 'Making Time Visible & Managing Tasks'),
    ('i_dont_have_time', 7, 'Making Time Visible & Managing Tasks'),
    ('i_dont_have_time', 16, 'Making Time Visible & Managing Tasks'),
    ('i_dont_have_time', 24, 'Making Time Visible & Managing Tasks'),
    ('i_dont_know_how', 10, 'Overcoming Mental Blocks & Reframing Shame'),
    ('i_dont_know_how', 14, 'Systems, Tools & Externalization'),
    ('i_dont_know_how', 37, 'Systems, Tools & Externalization'),
    ('i_dont_know_how', 13, 'Systems, Tools & Externalization'),
    ('i_feel_alone', 19, 'Practical Tools for Building Connection'),
    ('i_feel_emotionally_blocked', 9, 'Understanding Emotional Paralysis'),
    ('i_feel_emotionally_blocked', 15, 'Understanding Emotional Paralysis'),
    ('i_feel_emotionally_blocked', 32, 'Understanding Emotional Paralysis'),
    ('i_feel_alone', 6, 'Practical Tools for Building Connection'),
    ('i_feel_emotionally_blocked', 25, 'Understanding Emotional Paralysis'),
    ('i_feel_emotionally_blocked', 24, 'Barriers Beneath the Block'),
    ('i_feel_emotionally_blocked', 28, 'Understanding Emotional Paralysis'),
    ('i_feel_emotionally_blocked', 7, 'Barriers Beneath the Block'),
    ('i_feel_emotionally_blocked', 3, 'Barriers Beneath the Block'),
    ('i_feel_emotionally_blocked', 1, 'Understanding Emotional Paralysis'),
    ('i_feel_emotionally_blocked', 6, 'Understanding Emotional Paralysis'),
    ('i_dont_know_how', 12, 'Overcoming Mental Blocks & Reframing Shame'),
    ('i_dont_know_how', 2, 'Overcoming Mental Blocks & Reframing Shame'),
    ('i_dont_know_how', 1, 'Overcoming Mental Blocks & Reframing Shame'),
    ('i_dont_have_time', 6, 'Making Time Visible & Managing Tasks'),
    ('i_dont_know_how', 5, 'Systems, Tools & Externalization'),
    ('i_dont_have_time', 5, 'Making Time Visible & Managing Tasks'),
    ('i_dont_have_time', 19, 'Understanding ADHD & Time Blindness'),
    ('i_dont_have_time', 27, 'Understanding ADHD & Time Blindness'),
    ('i_dont_have_time', 17, 'Making Time Visible & Managing Tasks'),
    ('i_dont_have_time', 8, 'Making Time Visible & Managing Tasks'),
    ('i_dont_know_how', 19, 'Understanding Executive Function and ADHD'),
    ('i_dont_know_how', 25, 'Understanding Executive Function and ADHD'),
    ('i_dont_know_how', 22, 'Understanding Executive Function and ADHD'),
    ('i_dont_know_how', 27, 'Understanding Executive Function and ADHD'),
    ('i_dont_know_how', 34, 'Overcoming Mental Blocks & Reframing Shame'),
    ('i_dont_know_how', 16, 'Systems, Tools & Externalization'),
    ('i_dont_know_how', 48, 'Community, Coaching & Asking for Help'),
    ('i_dont_have_time', 25, 'Support & Self-Compassion'),
    ('i_dont_have_time', 3, 'Support & Self-Compassion'),
    ('i_dont_have_time', 28, 'Understanding ADHD & Time Blindness'),
    ('i_dont_have_time', 9, 'Support & Self-Compassion'),
    ('i_dont_have_time', 1, 'Making Time Visible & Managing Tasks'),
    ('i_dont_have_time', 25, 'Understanding ADHD & Time Blindness'),
    ('i_dont_know_how', 6, 'Understanding Executive Function and ADHD'),
    ('i_dont_know_how', 3, 'Understanding Executive Function and ADHD'),
    ('i_dont_know_how', 4, 'Community, Coaching & Asking for Help'),
    ('i_dont_have_time', 6, 'Understanding ADHD & Time Blindness'),
    ('i_dont_have_time', 6, 'Support & Self-Compassion'),
    ('i_dont_have_time', 4, 'Support & Self-Compassion'),
    ('i_dont_know_how', 31, 'Overcoming Mental Blocks & Reframing Shame'),
    ('i_dont_have_time', 31, 'Support & Self-Compassion'),
    ('i_dont_know_how', 23, 'Community, Coaching & Asking for Help'),
    ('i_dont_know_how', 46, 'Community, Coaching & Asking for Help'),
    ('i_dont_know_how', 7, 'Community, Coaching & Asking for Help'),
    ('i_dont_know_how', 8, 'Community, Coaching & Asking for Help'),
    ('i_dont_know_how', 17, 'Community, Coaching & Asking for Help'),
    ('i_feel_alone', 9, 'The Emotional Toll of Shame & Masking'),
    ('i_feel_emotionally_blocked', 17, 'Self-Compassion and Soft Starts'),
    ('i_feel_emotionally_blocked', 16, 'Self-Compassion and Soft Starts'),
    ('i_feel_shame', 9, 'Understanding ADHD Shame'),
    ('i_feel_shame', 30, 'Understanding ADHD Shame'),
    ('i_feel_shame', 9, 'Strategies to Release Shame'),
    ('i_feel_alone', 1, 'Understanding Loneliness & ADHD'),
    ('i_feel_emotionally_blocked', 8, 'Barriers Beneath the Block'),
    ('i_feel_emotionally_blocked', 2, 'Self-Compassion and Soft Starts'),
    ('i_feel_alone', 16, 'Understanding Loneliness & ADHD'),
    ('i_feel_shame', 33, 'Understanding ADHD Shame'),
    ('i_got_distracted', 5, 'Executive Function + Externalization'),
    ('i_got_distracted', 3, 'Executive Function + Externalization'),
    ('i_feel_shame', 1, 'Strategies to Release Shame'),
    ('i_feel_shame', 18, 'Understanding ADHD Shame'),
    ('i_feel_alone', 25, 'The Emotional Toll of Shame & Masking'),
    ('i_dont_know_how', 28, 'Community, Coaching & Asking for Help'),
    ('i_feel_emotionally_blocked', 31, 'Self-Compassion and Soft Starts'),
    ('i_feel_alone', 3, 'Understanding Loneliness & ADHD'),
    ('i_feel_alone', 8, 'Understanding Loneliness & ADHD'),
    ('i_feel_shame', 2, 'Strategies to Release Shame'),
    ('i_feel_alone', 7, 'Understanding Loneliness & ADHD'),
    ('i_feel_shame', 4, 'Strategies to Release Shame'),
    ('i_feel_emotionally_blocked', 4, 'Self-Compassion and Soft Starts'),
    ('i_feel_alone', 4, 'The Emotional Toll of Shame & Masking'),
    ('i_feel_emotionally_blocked', 12, 'Self-Compassion and Soft Starts'),
    ('i_feel_shame', 15, 'Strategies to Release Shame'),
    ('i_got_distracted', 27, 'Neurological Understanding of Distraction'),
    ('i_got_distracted', 15, 'Neurological Understanding of Distraction'),
    ('i_got_distracted', 19, 'Executive Function + Externalization'),
    ('i_got_distracted', 14, 'Executive Function + Externalization'),
    ('i_got_distracted', 34, 'Practical Strategies to Stay on Track'),
    ('i_got_distracted', 7, 'Practical Strategies to Stay on Track'),
    ('i_got_distracted', 16, 'Practical Strategies to Stay on Track'),
    ('i_got_distracted', 13, 'Support + Environment'),
    ('i_got_distracted', 6, 'Executive Function + Externalization'),
    ('i_feel_shame', 32, 'Understanding ADHD Shame'),
    ('i_feel_shame', 2, 'Understanding ADHD Shame'),
    ('i_feel_shame', 25, 'Understanding ADHD Shame'),
    ('i_feel_shame', 24, 'Strategies to Release Shame'),
    ('i_feel_shame', 6, 'Understanding ADHD Shame'),
    ('i_keep_avoiding_it', 3, 'Understanding Avoidance in ADHD Brains'),
    ('i_feel_shame', 12, 'Strategies to Release Shame'),
    ('i_feel_shame', 4, 'Understanding ADHD Shame'),
    ('i_feel_shame', 7, 'Understanding ADHD Shame'),
    ('i_feel_shame', 28, 'Understanding ADHD Shame'),
    ('i_feel_shame', 3, 'Understanding ADHD Shame'),
    ('i_got_distracted', 33, 'Neurological Understanding of Distraction'),
    ('i_feel_shame', 5, 'Understanding ADHD Shame'),
    ('i_keep_avoiding_it', 1, 'Understanding Avoidance in ADHD Brains'),
    ('i_keep_avoiding_it', 6, 'Understanding Avoidance in ADHD Brains'),
    ('i_feel_shame', 31, 'Understanding ADHD Shame'),
    ('i_got_distracted', 28, 'Self-Compassion + Reframing'),
    ('i_got_distracted', 2, 'Practical Strategies to Stay on Track'),
    ('i_got_distracted', 23, 'Practical Strategies to Stay on Track'),
    ('i_keep_avoiding_it', 17, 'Cognitive Frameworks to Name the Block'),
    ('i_keep_avoiding_it', 12, 'Strategy Tools to Make Action Feel Possible'),
    ('i_got_distracted', 1, 'Practical Strategies to Stay on Track'),
    ('i_run_out_of_steam', 16, 'Understanding ADHD Fatigue & Burnout'),
    ('im_afraid_ill_fail', 5, 'Tools, Coaching, and Self-Compassion'),
    ('i_run_out_of_steam', 8, 'Rest as a Right — Not a Reward'),
    ('i_run_out_of_steam', 10, 'Energy Management & Gentle Productivity'),
    ('i_run_out_of_steam', 20, 'Energy Management & Gentle Productivity'),
    ('im_afraid_ill_fail', 27, 'Naming Internal Barriers & Emotional Shields'),
    ('im_afraid_ill_fail', 2, 'Naming Internal Barriers & Emotional Shields'),
    ('im_afraid_ill_fail', 6, 'Tools, Coaching, and Self-Compassion'),
    ('im_afraid_ill_fail', 4, 'Naming Internal Barriers & Emotional Shields'),
    ('im_afraid_ill_fail', 8, 'Tools, Coaching, and Self-Compassion'),
    ('im_afraid_ill_fail', 16, 'Tools, Coaching, and Self-Compassion'),
    ('i_got_distracted', 25, 'Self-Compassion + Reframing'),
    ('i_run_out_of_steam', 6, 'Understanding ADHD Fatigue & Burnout'),
    ('i_run_out_of_steam', 28, 'Rest as a Right — Not a Reward'),
    ('i_run_out_of_steam', 3, 'Understanding ADHD Fatigue & Burnout'),
    ('i_run_out_of_steam', 4, 'Rest as a Right — Not a Reward'),
    ('i_run_out_of_steam', 31, 'Rest as a Right — Not a Reward'),
    ('i_keep_avoiding_it', 32, 'Emotional Roots + Compassionate Reframing'),
    ('i_keep_avoiding_it', 2, 'Emotional Roots + Compassionate Reframing'),
    ('i_keep_avoiding_it', 24, 'Cognitive Frameworks to Name the Block'),
    ('im_afraid_ill_fail', 3, 'Understanding ADHD, RSD, and Fear Loops'),
    ('im_afraid_ill_fail', 32, 'Reframing Failure & Building Resilience'),
    ('im_afraid_ill_fail', 18, 'Understanding ADHD, RSD, and Fear Loops'),
    ('im_afraid_ill_fail', 25, 'Understanding ADHD, RSD, and Fear Loops'),
    ('im_afraid_ill_fail', 46, 'Understanding ADHD, RSD, and Fear Loops'),
    ('im_afraid_ill_fail', 24, 'Naming Internal Barriers & Emotional Shields'),
    ('im_afraid_ill_fail', 10, 'Reframing Failure & Building Resilience'),
    ('i_keep_avoiding_it', 4, 'Emotional Roots + Compassionate Reframing'),
    ('it_feels_pointless', 28, 'Action Through Acceptance & Experimentation'),
    ('i_keep_avoiding_it', 43, 'Emotional Roots + Compassionate Reframing'),
    ('im_afraid_ill_fail', 1, 'Reframing Failure & Building Resilience'),
    ('i_run_out_of_steam', 46, 'Energy Management & Gentle Productivity'),
    ('i_keep_avoiding_it', 28, 'Emotional Roots + Compassionate Reframing'),
    ('i_run_out_of_steam', 2, 'Energy Management & Gentle Productivity'),
    ('i_keep_avoiding_it', 5, 'Understanding Avoidance in ADHD Brains'),
    ('it_feels_pointless', 10, 'Action Through Acceptance & Experimentation'),
    ('i_got_distracted', 31, 'Self-Compassion + Reframing'),
    ('it_feels_too_big', 28, 'Emotional Weight, Guilt & Shame'),
    ('it_feels_too_big', 1, 'Strategies, Support & Motivation'),
    ('it_feels_pointless', 43, 'Understanding ADHD Motivation & Inertia'),
    ('it_feels_too_big', 7, 'Strategies, Support & Motivation'),
    ('it_feels_too_big', 34, 'Strategies, Support & Motivation'),
    ('im_afraid_ill_fail', 28, 'Tools, Coaching, and Self-Compassion'),
    ('it_feels_pointless', 23, 'Understanding ADHD Motivation & Inertia'),
    ('it_feels_pointless', 5, 'Action Through Acceptance & Experimentation'),
    ('it_feels_too_big', 4, 'Emotional Weight, Guilt & Shame'),
    ('it_feels_pointless', 1, 'Reframing Pointlessness as Information'),
    ('it_feels_too_big', 42, 'Strategies, Support & Motivation'),
    ('im_afraid_ill_fail', 30, 'Tools, Coaching, and Self-Compassion'),
    ('it_feels_pointless', 42, 'Reframing Pointlessness as Information'),
    ('too_many_decisions', 43, 'Why ADHD Brains Struggle With Choices'),
    ('it_feels_too_big', 12, 'Reframing & Breaking Down the Task'),
    ('it_feels_too_big', 31, 'Emotional Weight, Guilt & Shame'),
    ('it_feels_too_big', 8, 'Understanding Overwhelm & Executive Dysfunction'),
    ('it_feels_too_big', 10, 'Reframing & Breaking Down the Task'),
    ('it_feels_too_big', 6, 'Reframing & Breaking Down the Task'),
    ('it_feels_too_big', 5, 'Strategies, Support & Motivation'),
    ('too_many_decisions', 6, 'Emotional Barriers, Guilt, & Self-Compassion'),
    ('too_many_decisions', 27, 'Emotional Barriers, Guilt, & Self-Compassion'),
    ('too_many_decisions', 28, 'Emotional Barriers, Guilt, & Self-Compassion'),
    ('too_many_decisions', 4, 'Emotional Barriers, Guilt, & Self-Compassion'),
    ('too_many_decisions', 12, 'Simplify Choices & Reduce Friction'),
    ('too_many_decisions', 42, 'Why ADHD Brains Struggle With Choices'),
    ('too_many_decisions', 5, 'Simplify Choices & Reduce Friction'),
    ('too_many_decisions', 1, 'Simplify Choices & Reduce Friction'),
    ('too_many_decisions', 13, 'Simplify Choices & Reduce Friction'),
    ('too_many_decisions', 34, 'Simplify Choices & Reduce Friction');