-- Create standardized sources table
DROP TABLE IF EXISTS standardized_sources CASCADE;

CREATE TABLE standardized_sources (
    id SERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    authors TEXT NOT NULL,
    description TEXT,
    total_appearances INTEGER DEFAULT 0,
    unique_pages INTEGER DEFAULT 0,
    categories TEXT[],
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE standardized_sources ENABLE ROW LEVEL SECURITY;

CREATE POLICY "standardized_sources_policy" ON standardized_sources
    FOR ALL TO PUBLIC USING (true);

-- Insert the top 57 sources
INSERT INTO standardized_sources (title, authors, description, total_appearances, unique_pages, categories) VALUES
    ('The Anti-Planner', 'Dani Donovan', 'Comprehensive resource for rest & self-compassion and strategies for managing anxiety.', 28, 21, '{"Rest & Self-Compassion", "Strategies for Managing Anxiety", "Self-Compassion & Self-Forgiveness", "Understanding Burnout & Energy Depletion", "Reframing, Agency & Tiny Action", "Clearing Clutter with Brain Dumps", "Energy-Conserving Systems & Real-Time Healing", "Boundaries, Overload & Powerlessness", "Externalizing Emotions & Reducing Self-Blame", "Self-Compassion & Reframing Shame", "Boundaries, Capacity & Saying No", "How ADHD Fuels Hopelessness", "You Don’t Have to Face This Alone", "Why ADHD Makes Loneliness Worse", "Mindfulness, Systems, and Mental Load", "Reframing, Self-Compassion, and Communication", "🔎 Recognizing Triggers & Early Warnings", "🪜 Baby Steps & Reducing Demands", "Self-Compassion, Shame, and Inner Critic Work", "Emotional Turbulence, Hopelessness & Disconnection", "Externalization: Free-Writing, Body Mapping & Naming Emotions", "Brain Dumps & Externalizing Chaos", "Reconnecting with the Body & Reframing Emotion", "Reduce Demands & Reclaim a Tiny Sense of Control", "Acknowledge & Process Emotions", "Reduce Demands & Reclaim Control", "Overcoming Mental Blocks & Reframing Shame", "Practical Tools for Remembering"}'),
    ('Tiny Experiments', 'Anne-Laure Le Cunff', 'Habit formation and behavior change strategies applicable to support networks & connection and strategies for managing anxiety.', 29, 20, '{"Support Networks & Connection", "Strategies for Managing Anxiety", "Physical & Emotional Release", "Tiny Steps, Self-Compassion, and Reframing", "Reframing, Agency & Tiny Action", "Reflection, Writing, & Emotional Processing", "Body Awareness, Interoception & Emotional Reframing", "Emotions as Signals, Not Enemies", "Understanding Guilt as a Signal (Not a Verdict)", "Recognizing Hopelessness as a Signal", "Emotional Dysregulation, Shame & Self-Protection", "Making Connection Possible Again", "Identity, Visibility & the Pain of Not Being Seen", "Why ADHD Can Lead to Numbness", "🔎 Recognizing Triggers & Early Warnings", "🪜 Baby Steps & Reducing Demands", "Self-Compassion, Shame, and Inner Critic Work", "Integration & Healing", "Externalization: Free-Writing, Body Mapping & Naming Emotions", "Executive Dysfunction, Attention, and the Scattered Mind", "Reconnecting with the Body & Reframing Emotion", "Acknowledge & Validate Your Emotions", "Rethink & Reframe Tasks", "Reduce Demands & Reclaim a Tiny Sense of Control", "Acknowledge & Process Emotions", "Reduce Demands & Reclaim Control", "Embrace Curiosity & Trust the Process", "Overcoming Mental Blocks & Reframing Shame", "ADHD Strategy & System Design"}'),
    ('Unapologetically ADHD', 'Kinzer & Wright', 'ADHD-focused resource covering rest & self-compassion, strategies for managing anxiety, reducing demands & taking baby steps.', 30, 18, '{"Rest & Self-Compassion", "Strategies for Managing Anxiety", "Reducing Demands & Taking Baby Steps", "Building Better Systems & External Memory", "Writing Things Down & Reminder Strategies", "Energy-Conserving Systems & Real-Time Healing", "Gentle Action & Systems for Support", "How ADHD Fuels Hopelessness", "You Don’t Have to Face This Alone", "Why ADHD Makes You Feel Misunderstood", "Tools to Reconnect Gently", "Why ADHD Gets Overstimulated So Easily", "🧠 Externalize, Organize, Simplify", "Understanding Rejection Sensitivity & Emotional Pain", "Emotional Turbulence, Hopelessness & Disconnection", "Brain Dumping & External Processing", "Executive Dysfunction, Attention, and the Scattered Mind", "Brain Dumps & Externalizing Chaos", "Tiny Steps When You’re All Over the Place", "Rethink & Reframe Tasks", "Reduce Demands & Reclaim a Tiny Sense of Control", "Reduce Demands & Reclaim Control", "Understanding ADHD & Energy Drain", "Motivation, Micro-Steps & Momentum", "Support, Coaching & Asking for Help", "Understanding ADHD & Time Blindness", "Making Time Visible & Managing Tasks", "Support & Self-Compassion", "Executive Function + Externalization", "Understanding Avoidance in ADHD Brains"}'),
    ('Real Self-Care', 'Pooja Lakshmin, M.D.', 'Self-care and compassion-focused approach to support networks & connection and boundaries & guilt management.', 28, 19, '{"Support Networks & Connection", "Boundaries & Guilt Management", "Therapy, Coaching & Professional Support", "Rest & Self-Compassion", "Self-Compassion & Self-Forgiveness", "Addressing the Roots of Shame", "Understanding Burnout & Energy Depletion", "Shame, Self-Blame & Inner Critics", "Rebuilding Hope & Addressing Hopelessness", "Energy-Conserving Systems & Real-Time Healing", "Boundaries, Overload & Powerlessness", "Understanding Guilt as a Signal (Not a Verdict)", "Boundaries, Capacity & Saying No", "Reframing, Micro-Steps & Meaning-Making", "You Don’t Have to Face This Alone", "Emotional Dysregulation, Shame & Self-Protection", "Making Connection Possible Again", "Rejection, Shame, and Shutdown", "Burnout, Shame & Emotional Shutdown", "🔎 Recognizing Triggers & Early Warnings", "🧘‍♀️ Emotional Regulation & Support", "Self-Compassion, Shame, and Inner Critic Work", "Integration & Healing", "Emotional Turbulence, Hopelessness & Disconnection", "Scaling Back & Finding Calm", "Acknowledge & Validate Your Emotions", "Set Boundaries, Reach Out, and Let Go", "Reduce Demands & Reclaim Control"}'),
    ('Order from Chaos', 'Jaclyn Paul', 'Comprehensive resource for rest & self-compassion and understanding & confronting shame.', 22, 19, '{"Rest & Self-Compassion", "Understanding & Confronting Shame", "Brain Clutter, Systems, & Recovery", "Emotional Overload, Hopelessness & Burnout", "Reflection, Writing, & Emotional Processing", "Reducing Demands & Taking Baby Steps", "Building Better Systems & External Memory", "Externalizing Emotions & Reducing Self-Blame", "Emotional Context & Community Understanding", "Reframing, Micro-Steps & Meaning-Making", "You Don’t Have to Face This Alone", "Why ADHD Makes Loneliness Worse", "Mindfulness, Systems, and Mental Load", "Healing Through Externalization & Support", "🧠 Externalize, Organize, Simplify", "Emotional Resilience, Identity & Boundaries", "Brain Dumping & External Processing", "Executive Dysfunction, Attention, and the Scattered Mind", "Brain Dumps & Externalizing Chaos", "Set Boundaries, Reach Out, and Let Go", "Systems, Tools & Externalization", "ADHD Strategy & System Design"}'),
    ('How to ADHD', 'Jessica McCabe', 'ADHD-focused resource covering support networks & connection, therapy, coaching & professional support, understanding & confronting shame.', 21, 19, '{"Support Networks & Connection", "Therapy, Coaching & Professional Support", "Understanding & Confronting Shame", "Shame, Self-Blame & Inner Critics", "Writing Things Down & Reminder Strategies", "Externalizing Emotions & Reducing Self-Blame", "Self-Compassion & Reframing Shame", "You Don’t Have to Face This Alone", "Tools for Self-Compassion, Naming & Externalizing", "Emotional Overwhelm, Shame, and Dysregulation", "Healing Through Externalization & Support", "🧠 Reducing Demands, Externalizing, & Getting Support", "🧠 Externalize, Organize, Simplify", "Understanding Rejection Sensitivity & Emotional Pain", "Emotional Turbulence, Hopelessness & Disconnection", "Executive Dysfunction, Attention, and the Scattered Mind", "Reconnecting with the Body & Reframing Emotion", "Set Boundaries, Reach Out, and Let Go", "Reduce Demands & Reclaim Control", "Understanding Executive Function and ADHD", "Practical Tools for Remembering"}'),
    ('How to Thrive with Adult ADHD', 'James Kustow', 'ADHD-focused resource covering support networks & connection, therapy, coaching & professional support, understanding & confronting shame.', 19, 18, '{"Support Networks & Connection", "Therapy, Coaching & Professional Support", "Understanding & Confronting Shame", "Emotional Overload, Hopelessness & Burnout", "Rebuilding Hope & Addressing Hopelessness", "Writing Things Down & Reminder Strategies", "Externalizing Emotions & Reducing Self-Blame", "Self-Compassion & Reframing Shame", "Why ADHD Makes Loneliness Worse", "Identity, Hormones, and Development", "Rejection, Shame, and Shutdown", "🧘‍♀️ Sensory Tools & Nervous System Soothing", "🧘‍♀️ Emotional Regulation & Support", "Understanding Rejection Sensitivity & Emotional Pain", "Emotional Turbulence, Hopelessness & Disconnection", "Executive Dysfunction, Attention, and the Scattered Mind", "Set Boundaries, Reach Out, and Let Go", "Reduce Demands & Reclaim Control", "Community, Coaching & Asking for Help"}'),
    ('Women with Attention Deficit Disorder', 'Sari Solden', 'Comprehensive resource for boundaries & guilt management and therapy, coaching & professional support.', 19, 16, '{"Boundaries & Guilt Management", "Therapy, Coaching & Professional Support", "Understanding & Confronting Shame", "Validation, Hope & Emotional Processing", "Boundaries, Overload & Powerlessness", "Self-Compassion & Reframing Shame", "Boundaries, Capacity & Saying No", "How ADHD Fuels Hopelessness", "You Don’t Have to Face This Alone", "Emotional Dysregulation, Shame & Self-Protection", "Identity, Hormones, and Development", "Identity, Visibility & the Pain of Not Being Seen", "Burnout, Shame & Emotional Shutdown", "🧠 Reducing Demands, Externalizing, & Getting Support", "Understanding ADHD Overwhelm", "Executive Dysfunction, Attention, and the Scattered Mind", "Set Boundaries, Reach Out, and Let Go", "Embrace Curiosity & Trust the Process", "Community, Coaching & Asking for Help"}'),
    ('The Neurodivergence Skills Workbook', 'Kemp & Mitchelson', 'Comprehensive resource for boundaries & guilt management and rest & self-compassion.', 19, 14, '{"Boundaries & Guilt Management", "Rest & Self-Compassion", "Physical & Emotional Release", "How ADHD Fuels Hopelessness", "Why ADHD Makes Loneliness Worse", "Why ADHD Makes You Feel Misunderstood", "Why ADHD Can Lead to Numbness", "Tools to Reconnect Gently", "Why ADHD Gets Overstimulated So Easily", "🧘‍♀️ Sensory Tools & Nervous System Soothing", "🧘‍♀️ Emotional Regulation & Support", "Understanding Rejection Sensitivity & Emotional Pain", "Externalization: Free-Writing, Body Mapping & Naming Emotions", "Reconnecting with the Body & Reframing Emotion", "Acknowledge & Validate Your Emotions", "Move & Ground Your Body", "Set Boundaries, Reach Out, and Let Go", "Acknowledge & Process Emotions", "Support & Self-Compassion"}'),
    ('Feel-Good Productivity', 'Ali Abdaal', 'Comprehensive resource for self-compassion & self-forgiveness and tiny steps, self-compassion, and reframing.', 15, 15, '{"Self-Compassion & Self-Forgiveness", "Tiny Steps, Self-Compassion, and Reframing", "Reframing, Agency & Tiny Action", "Rebuilding Hope & Addressing Hopelessness", "Emotions as Signals, Not Enemies", "Understanding Guilt as a Signal (Not a Verdict)", "Recognizing Hopelessness as a Signal", "Tools for Self-Compassion, Naming & Externalizing", "Reframing, Self-Compassion, and Communication", "🪜 Baby Steps & Reducing Demands", "Integration & Healing", "Reclaiming Control: Doing Less, Resting More", "Scaling Back & Finding Calm", "Acknowledge & Process Emotions", "Overcoming Mental Blocks & Reframing Shame"}'),
    ('Do Hard Things', 'Steve Magness', 'Comprehensive resource for strategies for managing anxiety and self-compassion & self-forgiveness.', 16, 14, '{"Strategies for Managing Anxiety", "Self-Compassion & Self-Forgiveness", "Emotions, Guilt & ADHD Recovery", "Validation, Hope & Emotional Processing", "Body Awareness, Interoception & Emotional Reframing", "Emotions as Signals, Not Enemies", "Understanding Guilt as a Signal (Not a Verdict)", "Tools for Self-Compassion, Naming & Externalizing", "Why ADHD Can Lead to Numbness", "Why ADHD Gets Overstimulated So Easily", "Emotional Turbulence, Hopelessness & Disconnection", "Externalization: Free-Writing, Body Mapping & Naming Emotions", "Reconnecting with the Body & Reframing Emotion", "Acknowledge & Validate Your Emotions", "Move & Ground Your Body", "Acknowledge & Process Emotions"}'),
    ('Tiny Habits', 'BJ Fogg', 'Habit formation and behavior change strategies applicable to self-compassion & self-forgiveness and tiny steps, self-compassion, and reframing.', 14, 14, '{"Self-Compassion & Self-Forgiveness", "Tiny Steps, Self-Compassion, and Reframing", "Reframing, Agency & Tiny Action", "Reducing Demands & Taking Baby Steps", "Baby Steps & Protecting Energy", "Gentle Action & Systems for Support", "Reframing, Micro-Steps & Meaning-Making", "Tools to Reconnect Gently", "🪜 Baby Steps & Reducing Demands", "Micro-Steps, Baby Steps & Self-Pacing", "Tiny Steps When You’re All Over the Place", "Rethink & Reframe Tasks", "Reduce Demands & Reclaim Control", "Overcoming Mental Blocks & Reframing Shame"}'),
    ('The Coaching Habit', 'Michael Bungay Stanier', 'Habit formation and behavior change strategies applicable to boundaries & guilt management and limiting beliefs, inner narratives & identity.', 13, 12, '{"Boundaries & Guilt Management", "Limiting Beliefs, Inner Narratives & Identity", "Boundaries, Overload & Powerlessness", "Gentle Action & Systems for Support", "Boundaries, Capacity & Saying No", "Tools for Self-Compassion, Naming & Externalizing", "Reframing, Self-Compassion, and Communication", "🔎 Recognizing Triggers & Early Warnings", "🧘‍♀️ Emotional Regulation & Support", "Emotional Resilience, Identity & Boundaries", "Set Boundaries, Reach Out, and Let Go", "Reduce Demands & Reclaim Control", "Systems, Tools & Externalization"}'),
    ('Building a Second Brain', 'Tiago Forte', 'Organization and external brain systems for brain clutter, systems, & recovery and building better systems & external memory.', 11, 11, '{"Brain Clutter, Systems, & Recovery", "Building Better Systems & External Memory", "Externalizing Emotions & Reducing Self-Blame", "Gentle Action & Systems for Support", "Mindfulness, Systems, and Mental Load", "🧠 Externalize, Organize, Simplify", "Brain Dumping & External Processing", "Brain Dumps & Externalizing Chaos", "Reduce Demands & Reclaim Control", "Systems, Tools & Externalization", "ADHD Strategy & System Design"}'),
    ('The Body Keeps the Score', 'Bessel van der Kolk, M.D.', 'Body-based and trauma-informed approaches to support networks & connection and physical & emotional release.', 12, 10, '{"Support Networks & Connection", "Physical & Emotional Release", "Validation, Hope & Emotional Processing", "Reflection, Writing, & Emotional Processing", "Body Awareness, Interoception & Emotional Reframing", "Externalizing Emotions & Reducing Self-Blame", "Recognizing Hopelessness as a Signal", "Emotional Dysregulation, Shame & Self-Protection", "Integration & Healing", "Emotional Turbulence, Hopelessness & Disconnection", "Externalization: Free-Writing, Body Mapping & Naming Emotions", "Reconnecting with the Body & Reframing Emotion"}'),
    ('The Disorganized Mind', 'Nancy A. Ratey', 'Organization and external brain systems for support networks & connection and understanding burnout & energy depletion.', 13, 9, '{"Support Networks & Connection", "Understanding Burnout & Energy Depletion", "Emotional Overload, Hopelessness & Burnout", "Working Memory, Cognitive Load & ADHD", "Building Better Systems & External Memory", "Externalizing Emotions & Reducing Self-Blame", "Gentle Action & Systems for Support", "Executive Function, Attention, and Working Memory", "Acknowledge & Validate Your Emotions", "Rethink & Reframe Tasks", "Set Boundaries, Reach Out, and Let Go", "Acknowledge & Process Emotions", "Reduce Demands & Reclaim Control"}'),
    ('Motivational Interviewing', 'Miller & Rollnick', 'Coaching and motivational strategies for externalizing emotions & reducing self-blame and gentle action & systems for support.', 11, 10, '{"Externalizing Emotions & Reducing Self-Blame", "Gentle Action & Systems for Support", "Recognizing Hopelessness as a Signal", "You Don’t Have to Face This Alone", "Tools for Self-Compassion, Naming & Externalizing", "Reframing, Self-Compassion, and Communication", "🧘‍♀️ Emotional Regulation & Support", "Emotional Resilience, Identity & Boundaries", "Embrace Curiosity & Trust the Process", "Making Time Visible & Managing Tasks", "Cognitive Frameworks to Name the Block"}'),
    ('Scattered Minds', 'Gabor Maté', 'Comprehensive resource for physical & emotional release and limiting beliefs, inner narratives & identity.', 10, 10, '{"Physical & Emotional Release", "Limiting Beliefs, Inner Narratives & Identity", "Understanding Guilt as a Signal (Not a Verdict)", "Identity, Hormones, and Development", "Healing Through Externalization & Support", "Why ADHD Gets Overstimulated So Easily", "Understanding ADHD Overwhelm", "Understanding Rejection Sensitivity & Emotional Pain", "Executive Dysfunction, Attention, and the Scattered Mind", "Acknowledge & Process Emotions"}'),
    ('The Smart but Scattered Guide to Success', 'Dawson & Guare', 'Comprehensive resource for reducing demands & taking baby steps and building better systems & external memory.', 10, 9, '{"Reducing Demands & Taking Baby Steps", "Building Better Systems & External Memory", "Externalizing Emotions & Reducing Self-Blame", "Gentle Action & Systems for Support", "🧠 Reducing Demands, Externalizing, & Getting Support", "🧠 Externalize, Organize, Simplify", "Micro-Steps, Baby Steps & Self-Pacing", "Executive Dysfunction, Attention, and the Scattered Mind", "Tiny Steps When You’re All Over the Place", "Reduce Demands & Reclaim Control"}'),
    ('Healthy Happy ADHD', 'Lisa Dee', 'ADHD-focused resource covering rest & self-compassion, self-compassion & self-forgiveness, emotions, guilt & adhd recovery.', 9, 9, '{"Rest & Self-Compassion", "Self-Compassion & Self-Forgiveness", "Emotions, Guilt & ADHD Recovery", "Emotional Context & Community Understanding", "Nutrition, Movement, and Lifestyle", "Dopamine-Seeking, Adrenaline & Sensory Spiral", "Understanding ADHD Overwhelm", "Self-Compassion, Shame, and Inner Critic Work", "Move & Ground Your Body"}'),
    ('Unapologetically ADHD', 'Nikki Kinzer & Pete D. Wright', 'ADHD-focused resource covering understanding & confronting shame, understanding burnout & energy depletion, shame, self-blame & inner critics.', 9, 9, '{"Understanding & Confronting Shame", "Understanding Burnout & Energy Depletion", "Shame, Self-Blame & Inner Critics", "Clearing Clutter with Brain Dumps", "Working Memory, Cognitive Load & ADHD", "Externalizing Emotions & Reducing Self-Blame", "Emotional Overwhelm, Shame, and Dysregulation", "Understanding Executive Function and ADHD", "ADHD Strategy & System Design"}'),
    ('The Neurodivergence Skills Workbook', 'Jennifer Kemp & Monique Mitchelson', 'Comprehensive resource for support networks & connection and self-compassion & self-forgiveness.', 8, 8, '{"Support Networks & Connection", "Self-Compassion & Self-Forgiveness", "Understanding Burnout & Energy Depletion", "Body Awareness, Interoception & Emotional Reframing", "Working Memory, Cognitive Load & ADHD", "Emotions as Signals, Not Enemies", "Understanding Guilt as a Signal (Not a Verdict)", "Recognizing Hopelessness as a Signal"}'),
    ('Mad About Money', 'Maddy Alexander-Grout', 'Comprehensive resource for support networks & connection and shame, self-blame & inner critics.', 8, 8, '{"Support Networks & Connection", "Shame, Self-Blame & Inner Critics", "Boundaries, Overload & Powerlessness", "How ADHD Fuels Hopelessness", "Identity, Hormones, and Development", "Emotional Turbulence, Hopelessness & Disconnection", "Reduce Demands & Reclaim Control", "Community, Coaching & Asking for Help"}'),
    ('Immunity to Change', 'Kegan & Lahey', 'Comprehensive resource for strategies for managing anxiety and reframing, micro-steps & meaning-making.', 8, 8, '{"Strategies for Managing Anxiety", "Reframing, Micro-Steps & Meaning-Making", "Emotional Dysregulation, Shame & Self-Protection", "Reframing, Self-Compassion, and Communication", "Emotional Resilience, Identity & Boundaries", "Reduce Demands & Reclaim a Tiny Sense of Control", "Making Time Visible & Managing Tasks", "Cognitive Frameworks to Name the Block"}'),
    ('You Mean I’m Not Lazy, Stupid or Crazy?!', 'Kelly & Ramundo', 'Comprehensive resource for baby steps & protecting energy and externalizing emotions & reducing self-blame.', 8, 8, '{"Baby Steps & Protecting Energy", "Externalizing Emotions & Reducing Self-Blame", "Self-Compassion & Reframing Shame", "You Don’t Have to Face This Alone", "Emotional Dysregulation, Shame & Self-Protection", "Healing Through Externalization & Support", "Tools to Reconnect Gently", "Why ADHD Gets Overstimulated So Easily"}'),
    ('The Anti-Planner', 'Donovan, Dani', 'Comprehensive resource for movement, music, & novelty and tools for managing distraction & filtering noise.', 9, 7, '{"Movement, Music, & Novelty", "Tools for Managing Distraction & Filtering Noise", "Mindset, Self-Compassion & Focus Reframing", "Motivation, Micro-Steps & Momentum", "Support, Coaching & Asking for Help", "Understanding Loneliness & ADHD", "Understanding Emotional Paralysis", "Strategies That Help", "Strategies to Release Shame"}'),
    ('Succeeding With Adult ADHD', 'Abigail L. Levrini', 'ADHD-focused resource covering therapy, coaching & professional support, strategies for managing anxiety, understanding & confronting shame.', 8, 7, '{"Therapy, Coaching & Professional Support", "Strategies for Managing Anxiety", "Understanding & Confronting Shame", "Working Memory, Cognitive Load & ADHD", "Externalizing Emotions & Reducing Self-Blame", "Self-Compassion & Reframing Shame", "Executive Function, Attention, and Working Memory", "Understanding Executive Function and ADHD"}'),
    ('A Radical Guide for Women with ADHD', 'Solden, Frank & Littman', 'ADHD-focused resource covering therapy, coaching & professional support, boundaries, overload & powerlessness, self-compassion & reframing shame.', 8, 7, '{"Therapy, Coaching & Professional Support", "Boundaries, Overload & Powerlessness", "Self-Compassion & Reframing Shame", "How ADHD Fuels Hopelessness", "Understanding ADHD & Energy Drain", "Burnout, Rest & Recovery", "Understanding ADHD & Time Blindness", "Emotional Roots + Compassionate Reframing"}'),
    ('How to ADHD', 'McCabe, Jessica', 'ADHD-focused resource covering tools for managing distraction & filtering noise, managing time, hyperfocus & mental energy, movement, sensory support, & focus regulation.', 9, 6, '{"Tools for Managing Distraction & Filtering Noise", "Managing Time, Hyperfocus & Mental Energy", "Movement, Sensory Support, & Focus Regulation", "Nutrition, Movement & Sleep", "Support, Coaching & Asking for Help", "Practical Tools for Building Connection", "Understanding Emotional Paralysis", "Why Freezing Happens", "Understanding ADHD Shame"}'),
    ('The ADHD Effect on Marriage', 'Melissa Orlov', 'ADHD-focused resource covering understanding & confronting shame, emotional overload, hopelessness & burnout, making connection possible again.', 7, 7, '{"Understanding & Confronting Shame", "Emotional Overload, Hopelessness & Burnout", "Making Connection Possible Again", "Emotional Overwhelm, Shame, and Dysregulation", "Why ADHD Makes You Feel Misunderstood", "🧘‍♀️ Emotional Regulation & Support", "Emotional Resilience, Identity & Boundaries"}'),
    ('How to Keep House While Drowning', 'KC Davis', 'Comprehensive resource for addressing the roots of shame and mindfulness, systems, and mental load.', 7, 7, '{"Addressing the Roots of Shame", "Mindfulness, Systems, and Mental Load", "🧠 Reducing Demands, Externalizing, & Getting Support", "Self-Compassion, Shame, and Inner Critic Work", "Reclaiming Control: Doing Less, Resting More", "Scaling Back & Finding Calm", "Overcoming Mental Blocks & Reframing Shame"}'),
    ('The Mountain Is You', 'Brianna Wiest', 'Comprehensive resource for limiting beliefs, inner narratives & identity and rebuilding hope & addressing hopelessness.', 7, 7, '{"Limiting Beliefs, Inner Narratives & Identity", "Rebuilding Hope & Addressing Hopelessness", "Understanding Guilt as a Signal (Not a Verdict)", "Reframing, Micro-Steps & Meaning-Making", "Tools for Self-Compassion, Naming & Externalizing", "Rejection, Shame, and Shutdown", "Acknowledge & Process Emotions"}'),
    ('ADHD 2.0', 'Hallowell & Ratey', 'ADHD-focused resource covering emotional context & community understanding, why adhd makes loneliness worse, dopamine-seeking, adrenaline & sensory spiral.', 7, 7, '{"Emotional Context & Community Understanding", "Why ADHD Makes Loneliness Worse", "Dopamine-Seeking, Adrenaline & Sensory Spiral", "Executive Dysfunction, Attention, and the Scattered Mind", "Movement, Sensory Support, & Focus Regulation", "Nutrition, Movement & Sleep", "Neurological Understanding of Distraction"}'),
    ('It All Makes Sense Now', 'Meredith Carder', 'Comprehensive resource for understanding & confronting shame and identity, hormones, and development.', 7, 6, '{"Understanding & Confronting Shame", "Identity, Hormones, and Development", "Why ADHD Gets Overstimulated So Easily", "🧘‍♀️ Sensory Tools & Nervous System Soothing", "Understanding Rejection Sensitivity & Emotional Pain", "Executive Dysfunction, Attention, and the Scattered Mind", "Overcoming Mental Blocks & Reframing Shame"}'),
    ('The Body Keeps the Score', 'Bessel van der Kolk', 'Body-based and trauma-informed approaches to nutrition, movement, and lifestyle and why adhd can lead to numbness.', 7, 6, '{"Nutrition, Movement, and Lifestyle", "Why ADHD Can Lead to Numbness", "Why ADHD Gets Overstimulated So Easily", "Understanding ADHD Overwhelm", "Acknowledge & Validate Your Emotions", "Move & Ground Your Body", "Acknowledge & Process Emotions"}'),
    ('Brain Brilliance', 'Lucinda Miller', 'Organization and external brain systems for strategies for managing anxiety and physical & emotional release.', 6, 6, '{"Strategies for Managing Anxiety", "Physical & Emotional Release", "Externalizing Emotions & Reducing Self-Blame", "Emotional Context & Community Understanding", "Nutrition, Movement, and Lifestyle", "Dopamine-Seeking, Adrenaline & Sensory Spiral"}'),
    ('The PARA Method', 'Tiago Forte', 'Comprehensive resource for brain clutter, systems, & recovery and building better systems & external memory.', 6, 6, '{"Brain Clutter, Systems, & Recovery", "Building Better Systems & External Memory", "Externalizing Emotions & Reducing Self-Blame", "Gentle Action & Systems for Support", "🧠 Externalize, Organize, Simplify", "Systems, Tools & Externalization"}'),
    ('You Mean I’m Not Lazy, Stupid, or Crazy?!', 'Kelly & Ramundo', 'Comprehensive resource for self-compassion, shame, and inner critic work and micro-steps, baby steps & self-pacing.', 6, 5, '{"Self-Compassion, Shame, and Inner Critic Work", "Micro-Steps, Baby Steps & Self-Pacing", "Tiny Steps When You’re All Over the Place", "Acknowledge & Validate Your Emotions", "Rethink & Reframe Tasks", "Reduce Demands & Reclaim Control"}'),
    ('Real Self-Care', 'Lakshmin, Pooja', 'Self-care and compassion-focused approach to burnout, rest & recovery and the emotional toll of shame & masking.', 6, 5, '{"Burnout, Rest & Recovery", "The Emotional Toll of Shame & Masking", "Self-Compassion and Soft Starts", "Emotional Root Causes", "Understanding ADHD Shame", "Strategies to Release Shame"}'),
    ('Immunity to Change', 'Robert Kegan & Lisa Lahey', 'Comprehensive resource for boundaries & guilt management and understanding & confronting shame.', 5, 5, '{"Boundaries & Guilt Management", "Understanding & Confronting Shame", "Limiting Beliefs, Inner Narratives & Identity", "Rebuilding Hope & Addressing Hopelessness", "Boundaries, Overload & Powerlessness"}'),
    ('How to Thrive with Adult ADHD', 'Kustow, James', 'ADHD-focused resource covering managing time, hyperfocus & mental energy, support, coaching & asking for help, understanding loneliness & adhd.', 5, 5, '{"Managing Time, Hyperfocus & Mental Energy", "Support, Coaching & Asking for Help", "Understanding Loneliness & ADHD", "Barriers Beneath the Block", "Understanding ADHD Shame"}'),
    ('Tiny Experiments', 'Le Cunff, Anne-Laure', 'Habit formation and behavior change strategies applicable to burnout, rest & recovery and motivation, micro-steps & momentum.', 6, 4, '{"Burnout, Rest & Recovery", "Motivation, Micro-Steps & Momentum", "Self-Compassion and Soft Starts", "Strategies That Help", "Understanding ADHD Shame", "Strategies to Release Shame"}'),
    ('The Neurodivergence Skills Workbook', 'Kemp, Jennifer & Mitchelson, Monique', 'Comprehensive resource for understanding adhd & attention and the emotional toll of shame & masking.', 5, 4, '{"Understanding ADHD & Attention", "The Emotional Toll of Shame & Masking", "Understanding Emotional Paralysis", "Understanding ADHD Shame", "Strategies to Release Shame"}'),
    ('It All Makes Sense Now', 'Carder, Meredith', 'Comprehensive resource for understanding adhd & attention and burnout, rest & recovery.', 5, 4, '{"Understanding ADHD & Attention", "Burnout, Rest & Recovery", "Motivation, Micro-Steps & Momentum", "The Emotional Toll of Shame & Masking", "Barriers Beneath the Block"}'),
    ('The Smart but Scattered Guide to Success', 'Peg Dawson & Richard Guare', 'Comprehensive resource for brain clutter, systems, & recovery and reframing, agency & tiny action.', 4, 4, '{"Brain Clutter, Systems, & Recovery", "Reframing, Agency & Tiny Action", "Executive Function, Attention, and Working Memory", "Understanding Executive Function and ADHD"}'),
    ('Small Talk: 10 ADHD Lies', 'Richard & Roxanne Pink', 'ADHD-focused resource covering limiting beliefs, inner narratives & identity, self-compassion & reframing shame, how adhd fuels hopelessness.', 4, 4, '{"Limiting Beliefs, Inner Narratives & Identity", "Self-Compassion & Reframing Shame", "How ADHD Fuels Hopelessness", "Why ADHD Makes Loneliness Worse"}'),
    ('How to Thrive with Adult ADHD', 'Kustow', 'ADHD-focused resource covering reducing demands & taking baby steps, baby steps & protecting energy, making time visible & managing tasks.', 4, 4, '{"Reducing Demands & Taking Baby Steps", "Baby Steps & Protecting Energy", "Making Time Visible & Managing Tasks", "Practical Strategies to Stay on Track"}'),
    ('The Neurodiversity Edge', 'Maureen Dunne', 'Comprehensive resource for emotional context & community understanding and identity, hormones, and development.', 4, 4, '{"Emotional Context & Community Understanding", "Identity, Hormones, and Development", "🧘‍♀️ Sensory Tools & Nervous System Soothing", "Community, Coaching & Asking for Help"}'),
    ('Succeeding with Adult ADHD', 'Levrini', 'ADHD-focused resource covering healing through externalization & support, tiny steps when you’re all over the place, understanding adhd & time blindness.', 4, 4, '{"Healing Through Externalization & Support", "Tiny Steps When You’re All Over the Place", "Understanding ADHD & Time Blindness", "Neurological Understanding of Distraction"}'),
    ('The Disorganized Mind', 'Nancy Ratey', 'Organization and external brain systems for understanding adhd overwhelm and executive dysfunction, attention, and the scattered mind.', 4, 4, '{"Understanding ADHD Overwhelm", "Executive Dysfunction, Attention, and the Scattered Mind", "Systems, Tools & Externalization", "The Science of ADHD & Memory"}'),
    ('Unapologetically ADHD', 'Kinzer, Nikki & Wright, Pete D', 'ADHD-focused resource covering understanding loneliness & adhd, barriers beneath the block, why freezing happens.', 4, 4, '{"Understanding Loneliness & ADHD", "Barriers Beneath the Block", "Why Freezing Happens", "Understanding ADHD Shame"}'),
    ('Kinzer, N., & Wright, P. D. (2024). _Unapologetically ADHD_.', '', 'ADHD-focused resource covering action through acceptance & experimentation, emotional weight, guilt & shame, why urgency helps adhd brains activate.', 4, 4, '{"Action Through Acceptance & Experimentation", "Emotional Weight, Guilt & Shame", "Why Urgency Helps ADHD Brains Activate", "Why ADHD Brains Struggle With Choices"}'),
    ('Paul, J. (2018). _Order from Chaos_.', '', 'Comprehensive resource for action through acceptance & experimentation and strategies, support & motivation.', 4, 4, '{"Action Through Acceptance & Experimentation", "Strategies, Support & Motivation", "Planning Systems, Prompts & Activation Tools", "Simplify Choices & Reduce Friction"}'),
    ('How to ADHD', 'McCabe', 'ADHD-focused resource covering understanding adhd & time blindness, making time visible & managing tasks, support & self-compassion.', 5, 3, '{"Understanding ADHD & Time Blindness", "Making Time Visible & Managing Tasks", "Support & Self-Compassion", "Executive Function + Externalization", "Understanding Avoidance in ADHD Brains"}'),
    ('You Mean I''m Not Lazy, Stupid or Crazy?!', 'Kelly & Ramundo', 'Comprehensive resource for reducing demands & taking baby steps and understanding adhd overwhelm.', 4, 3, '{"Reducing Demands & Taking Baby Steps", "Understanding ADHD Overwhelm", "Understanding ADHD & Time Blindness", "Support & Self-Compassion"}'),
    ('Order from Chaos', 'Paul, Jaclyn', 'Comprehensive resource for tools for managing distraction & filtering noise and mindset, self-compassion & focus reframing.', 4, 3, '{"Tools for Managing Distraction & Filtering Noise", "Mindset, Self-Compassion & Focus Reframing", "Strategies That Help", "Understanding ADHD Shame"}'),
    ('Kustow, James.', '', 'Comprehensive resource for understanding tension in adhd and regulating the nervous system.', 5, 2, '{"Understanding Tension in ADHD", "Regulating the Nervous System", "Calming Mental Overload", "Support & Boundaries", "Understanding the Wired State in ADHD"}');

-- Create junction tables for standardized sources
DROP TABLE IF EXISTS feeling_standardized_sources CASCADE;
DROP TABLE IF EXISTS barrier_standardized_sources CASCADE;

CREATE TABLE feeling_standardized_sources (
    id SERIAL PRIMARY KEY,
    feeling_slug TEXT NOT NULL,
    source_id INTEGER REFERENCES standardized_sources(id),
    category TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE barrier_standardized_sources (
    id SERIAL PRIMARY KEY,
    barrier_slug TEXT NOT NULL,
    source_id INTEGER REFERENCES standardized_sources(id),
    category TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE feeling_standardized_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE barrier_standardized_sources ENABLE ROW LEVEL SECURITY;

CREATE POLICY "feeling_standardized_sources_policy" ON feeling_standardized_sources FOR ALL TO PUBLIC USING (true);
CREATE POLICY "barrier_standardized_sources_policy" ON barrier_standardized_sources FOR ALL TO PUBLIC USING (true);

CREATE INDEX idx_feeling_standardized_sources_feeling ON feeling_standardized_sources(feeling_slug);
CREATE INDEX idx_feeling_standardized_sources_source ON feeling_standardized_sources(source_id);
CREATE INDEX idx_barrier_standardized_sources_barrier ON barrier_standardized_sources(barrier_slug);
CREATE INDEX idx_barrier_standardized_sources_source ON barrier_standardized_sources(source_id);